- hosts: localhost
  connection: local 
  gather_facts: False 
  tasks:
    - name: including variable file
      include_vars: vpc_setup

    - name: including output variable file
      include_vars: output_vars

    - name: creating key for bastion host
      ec2_key:
        name: bastion_host_key
        region: "{{region}}"
      register: key_out

    - name: copying private key content in file 
      copy:
        content: "{{key_out.key.private_key}}"
        dest: bastion_key.pem
        mode: 0600
      when: key_out.changed

    - name: creating Security Group for bastion host
      ec2_group:
        name: bastion-SG
        description: This SG is for bastion host allowing Traffic on port 22 
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
          - from_port: 22
          - to_port: 22
          - cidr: "{{MYIP}}"
      register: bastionSG_out

    - name: Creating Bastion host
      ec2:
        key_name: bastion_host_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: Bastion_host
          Project: infra
          Owner: Devops 
        exact_count: 1
        count_tag:
          Name: Bastion_host
          Project: infra
          Owner: Devops
        group_id: "{{bastionSG_out.group_id}}"
        vpc_subnet_id: "{{Pubsub1id}}"
      register: bastion_host_out
          
          



    