---
- name: ec2 stack 
  hosts: localhost
  connection: local 
  gather_facts: False 
  tasks:
    - name: import vpc variable file
      include_vars: output_vars

    - name: import vpc variable file
      include_vars: Images

    - name: Creating an ec2 key for instance 
      ec2_key:
        name: stack-key
        region: "{{region}}"
      register: key_out

    - name: copying the content of private key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: stack-key.pem
        mode: 0600
      when: key_out.changed
