- hosts: localhost
  connection: local 
  gather_facts: False
  tasks:
    - name: import VPC variable
      include_vars: vpc_setup

    - name: create vpc 
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default 
        state: "{{state}}"
      register: vpc_info_out

    - debug:
        var: vpc_info_out 

    - name: creating public subnet in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub1}}"
        az: "{{zone1}}"

