- hosts: localhost
  connection: local 
  gather_facts: False
  tasks:
    - name: import VPC variable
      include_vars: vpc_setup

    - name: create vpc 
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default 
        state: "{{state}}"
      register: vpc_info_out

    - debug:
        var: vpc_info_out 

    - name: creating public subnet1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub1}}"
        az: "{{zone1}}"
        map_public: yes
        resource_tags:
          Name: publicsub1
      register: publicsub1_out

    - name: creating public subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub2}}"
        az: "{{zone2}}"
        map_public: yes
        resource_tags:
          Name: publicsub2
      register: publicsub2_out

    
    - name: creating public subnet3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub3}}"
        az: "{{zone3}}"
        map_public: yes
        resource_tags:
          Name: publicsub3
      register: publicsub3_out

    
    - name: creating private subnet1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Privatesub1}}"
        az: "{{zone1}}"
        resource_tags:
          Name: privatesub1
      register: privatesub1_out

    - name: creating private subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Privatesub2}}"
        az: "{{zone2}}"
        resource_tags:
          Name: privatesub2
      register: privatesub2_out

    - name: creating private subnet3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Privatesub3}}"
        az: "{{zone3}}"
        resource_tags:
          Name: privatesub3
      register: privatesub3_out   

    
    