- hosts: localhost
  connection: local 
  gather_facts: False
  tasks:
    - name: import VPC variable
      include_vars: vpc_setup

    - name: create vpc 
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpccidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default 
        state: "{{state}}"
      register: vpc_info_out

    - debug:
        var: vpc_info_out 

    - name: creating public subnet1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub1}}"
        az: "{{zone1}}"
        map_public: yes
        resource_tags:
          Name: publicsub1
      register: publicsub1_out

    - name: creating public subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub2}}"
        az: "{{zone2}}"
        map_public: yes
        resource_tags:
          Name: publicsub2
      register: publicsub2_out

    
    - name: creating public subnet3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Publicsub3}}"
        az: "{{zone3}}"
        map_public: yes
        resource_tags:
          Name: publicsub3
      register: publicsub3_out

    
    - name: creating private subnet1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Privatesub1}}"
        az: "{{zone1}}"
        resource_tags:
          Name: privatesub1
      register: privatesub1_out

    - name: creating private subnet2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Privatesub2}}"
        az: "{{zone2}}"
        resource_tags:
          Name: privatesub2
      register: privatesub2_out

    - name: creating private subnet3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        cidr: "{{Privatesub3}}"
        az: "{{zone3}}"
        resource_tags:
          Name: privatesub3
      register: privatesub3_out 

    - name: Creating Internet Gateway for VPC
      ec2_vpc_igw:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: vprofile_IGW
      register: IGW_out

    - name: Creating Route table for public subnets
      ec2_vpc_route_table:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Public-RouteTable-Vprofile
        subnets:
          - "{{publicsub1_out.subnet.id}}"
          - "{{publicsub2_out.subnet.id}}"
          - "{{publicsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{IGW_out.gateway_id}}"
      register: publicRoute_out  

    - name: Creating NAT Gateway for Private Subnets
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        region: "{{region}}"
        subnet_id: "{{publicsub1_out.subnet.id}}"
        wait: yes
        if_exist_do_not_create: true 
      register: NatGW_out 

    - name: Creating Route table for Private subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpc_info_out.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: Private-RouteTable-Vprofile
        subnets:
          - "{{privatesub1_out.subnet.id}}"
          - "{{privatesub2_out.subnet.id}}"
          - "{{privatesub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{NatGW_out.nat_gateway_id}}"
      register: PrivateRT_out

    - debug:
        var: "{{item}}"
      loop:
        - vpc_info_out.vpc.id
        - publicsub1_out.subnet.id
        - publicsub2_out.subnet.id
        - publicsub3_out.subnet.id
        - privatesub1_out.subnet.id
        - privatesub2_out.subnet.id
        - privatesub3_out.subnet.id
        - IGW_out.gateway_id
        - publicRoute_out.route_table.id
        - NatGW_out.nat_gateway_id
        - PrivateRT_out.route_table.id

    
    