- name: Installing the mysql server 
  hosts: dbservergroup
  gather_facts: no 
  tasks:
    - name: Installing required packages for SQL server
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
      tags:
        - package

    - name: starting and enabling mysql service 
      service:
        name: mysql
        state: started
        enabled: yes
      tags:
        - svc

    - name: creating mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: "*.*:ALL"
        host: "%"
        state: present

    - name: Creating database 
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: enable remote login to sql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql 
      tags:
        - conf

    handlers:
      name: Restart mysql 
      service:
        name: mysql 
        state: restarted  